---
- name: Install Prometheus, Node Exporter and prerequisites for Grafana
  apt:
    name:
    - prometheus
    - prometheus-node-exporter
    - apt-transport-https
    - software-properties-common
    state: present

- name: Ensure Prometheus and Prometheus Node Exporter override directories exist
  file:
    path: "/etc/systemd/system/{{ item }}.service.d"
    state: directory
    mode: '0755'
  with_items:
  - prometheus
  - prometheus-node-exporter

- name: Create Node Exporter systemd override file
  copy:
    dest: /etc/systemd/system/prometheus-node-exporter.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/prometheus-node-exporter --web.listen-address=127.0.0.1:9100 $ARGS 
    mode: '0644'

- name: Create Prometheus systemd override file
  copy:
    dest: /etc/systemd/system/prometheus.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/prometheus --web.listen-address=127.0.0.1:9090 $ARGS 
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Restart Node Exporter service
  systemd:
    name: prometheus-node-exporter
    state: restarted

- name: Configure Prometheus
  template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: Restart Prometheus service
  systemd:
    name: prometheus
    state: restarted

- name: Create keyrings directory for Grafana
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Grafana GPG key
  shell: "wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/keyrings/grafana.gpg"
  args:
    creates: /etc/apt/keyrings/grafana.gpg

- name: Add Grafana repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
    state: present
    filename: grafana

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Set Grafana HTTP address to localhost
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^http_addr\s*='
    line: 'http_addr = 127.0.0.1'

- name: Enable and start Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: restarted
